# Generated by Django 5.2 on 2025-05-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opiniones',
            new_name='Opinion',
        ),
    ]
